services:
  - type: web
    name: sf-alumnos-backend
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://federicosanchez.com.ar
        
databases:
  - name: sf-alumnos-mongodb
    databaseName: sf_alumnos
    user: sf_admin
    plan: free
